### ISSUE TITLE
make lint not working - cannot find package "golang.org/x/tools/go/gcimporter

### ISSUE THREAD

**Issue by jedi4ever** [jszwedko/go-circleci#6] opened 2016-11-21 07:55 UTC
```
$ make lint
package golang.org/x/tools/go/gcimporter: cannot find package "golang.org/x/tools/go/gcimporter" in any of:
        /usr/local/Cellar/go/1.7.3/libexec/src/golang.org/x/tools/go/gcimporter (from $GOROOT)
        /Users/patrick/go/src/golang.org/x/tools/go/gcimporter (from $GOPATH)
```

**Comment by jszwedko** [comment] 2016-11-22 03:31
I think you encountered this on `circleci-cli` rather than this library, but I'm not able to reproduce this by uninstalling `golint` and running `make lint` (the latter reinstalls it).

Can you try `go get -x -u github.com/golang/lint/golint` and let me know what that gives you?

**Comment by jszwedko** [comment] 2017-01-10 05:04
Closing this out, but please reopen if you are still running into this issue!

**Closed as completed by jszwedko** 2017-01-10 05:04 UTC
