### ISSUE TITLE
Some values returned by the API should be unescaped 

### ISSUE THREAD

**Issue by mstrzele** [jszwedko/go-circleci#17] opened 2017-11-23 10:21 UTC
When I'm trying to list all branches in a project (`project.Branches`), I'm getting the string which looks like this:
```
release%2F0%2E1%2E0
```
IMHO, the output should be unescaped (maybe by the `url.QueryUnescape()` function?)

**Comment by jszwedko** [comment] 2017-11-28 04:27
Hi @mstrzele !

I'm unable to reproduce this issue. I created a branch called `release/0.1.0` in [jszwedko/circleci-cli](https://github.com/jszwedko/circleci-cli/tree/release/0.1.0) and used:

```go
import (
	"fmt"

	"github.com/jszwedko/go-circleci"
)

func main() {
	client := &circleci.Client{Token: ""}

	builds, _ := client.ListRecentBuildsForProject("jszwedko", "circleci-cli", "release/test", "", -1, 0)

	for _, build := range builds {
		fmt.Printf("%d: %s %s\n", build.BuildNum, build.Branch, build.Status)
	}
}
```

Receiving the output:

```
68: release/0.1.0 running                                                                                                                                                                        
```

Do you have an example public project that exhibits this issue that I could take a look at?

**Comment by mstrzele** [comment] 2017-11-28 08:55
It occurs only when you want to use the name of the branch from the `project.Branches` map.

```
package main

import (
	"fmt"
	"os"

	"github.com/jszwedko/go-circleci"
)

func main() {
	client := &circleci.Client{Token: os.Getenv("CIRCLE_TOKEN")}

	project, _ := client.GetProject("mstrzele", "go-circleci")

	for branch, _ := range project.Branches {
		fmt.Println(branch)
	}
}
```

```
$ go run main.go
master
release%2F0%2E1%2E0
```

https://circleci.com/gh/mstrzele/go-circleci

**Comment by jszwedko** [comment] 2017-12-03 21:59
@mstrzele interesting, I see this as well. I feel like this is a bug that should be addressed in the API so I opened a bug report over in the CircleCI community support: https://discuss.circleci.com/t/api-returns-url-encoded-branch-names-in-json-response/18524 . We'll see what they say. If they don't wish to change it, we can consider decoding it in this library.

Thanks for bringing this up!

**Comment by jszwedko** [comment] 2017-12-12 16:46
Got a response back from CircleCI. The behavior was not intentional, but they are reticent to change it in case people have come to depend on it.

I think it's reasonable to have the SDK URL decode the value.

**Comment by jszwedko** [comment] 2017-12-12 17:20
@mstrzele let me know what you think of #18 -- thanks again for catching this behavior.

**Comment by mstrzele** [comment] 2017-12-13 09:16
@jszwedko looks good! thanks for your quick help with this and for this great library :)

**Comment by jszwedko** [comment] 2017-12-15 19:56
Merged, thanks for taking a look!

**Closed as completed** 2017-12-15 19:56 UTC
